/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje2.deneme.pkg1;

/**
 *
 * @author reyha
 */
public class adminpanel extends javax.swing.JFrame {

    /**
     * Creates new form adminpanel
     */
    public adminpanel() {
        initComponents();
        firmalarilistele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firmaadialani = new javax.swing.JTextField();
        firmagirisadialani = new javax.swing.JTextField();
        firmasifrealani = new javax.swing.JTextField();
        hizmetgir = new javax.swing.JTextField();
        mesajyazisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        firmalartablosu = new javax.swing.JTable();
        firmacikarbuton = new javax.swing.JButton();
        firmaeklebuton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        menu.setBackground(new java.awt.Color(102, 102, 102));
        menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("menü");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Firma Adı:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Firma Giriş Adı:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Firma Şifresi:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Hizmet Bedeli:");

        firmaadialani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firmaadialaniActionPerformed(evt);
            }
        });

        firmalartablosu.setBackground(new java.awt.Color(204, 204, 204));
        firmalartablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Firma Adı", "Firma Giriş Adı", "Firma Şifresi", "Hizmet Bedeli"
            }
        ));
        firmalartablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firmalartablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(firmalartablosu);

        firmacikarbuton.setBackground(new java.awt.Color(204, 0, 0));
        firmacikarbuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firmacikarbuton.setForeground(new java.awt.Color(255, 255, 255));
        firmacikarbuton.setText("Firma Çıkar");
        firmacikarbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firmacikarbutonActionPerformed(evt);
            }
        });

        firmaeklebuton.setBackground(new java.awt.Color(0, 204, 0));
        firmaeklebuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firmaeklebuton.setForeground(new java.awt.Color(255, 255, 255));
        firmaeklebuton.setText("Firma Ekle");
        firmaeklebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firmaeklebutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hizmetgir, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(firmasifrealani))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firmacikarbuton)
                            .addComponent(firmaeklebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(213, 213, 213))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(firmaadialani, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(firmagirisadialani))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesajyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firmaadialani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firmagirisadialani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firmasifrealani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firmaeklebuton))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hizmetgir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firmacikarbuton))
                .addGap(35, 35, 35)
                .addComponent(mesajyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      void firmalarilistele() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) firmalartablosu.getModel();

        // Örnek araçlar ekleyelim (gerçek veritabanından veya başka bir kaynaktan alabilirsiniz)
        Object[] arac1 = {"Firma A", "firmaA", "123","1000"};
        Object[] arac2 = {"Firma B", "firmaB", "1234","1000"};  
        Object[] arac3 = {"Firma C", "firmaC", "12345","1000"}; 
        Object[] arac4 = {"Firma D", "firmaD", "123456","1000"}; 
        Object[] arac5 = {"Firma F", "firmaF", "1234567","1000"}; 
       
        // Mevcut tabloya örnek verileri ekle
        model.addRow(arac1);
        model.addRow(arac2);
        model.addRow(arac3);
        model.addRow(arac4);
        model.addRow(arac5);
    }
                                            


    private void firmaadialaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firmaadialaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firmaadialaniActionPerformed

    private void firmacikarbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firmacikarbutonActionPerformed
        mesajyazisi.setText("");
        javax.swing.table.DefaultTableModel model =(javax.swing.table.DefaultTableModel)firmalartablosu.getModel();
     int secilirow=firmalartablosu.getSelectedRow();
     if(secilirow == -1)
     {  
         if(firmalartablosu.getRowCount() == 0)
         { 
             mesajyazisi.setText("Tablo su anda bos");
         }
         else
         {
           mesajyazisi.setText("secilecek satir secin");   
         }   
     }
     else
     {
         model.removeRow(secilirow);
         mesajyazisi.setText("urun basariyla silindi");
     }
  
// TODO add your handling code here:
    }//GEN-LAST:event_firmacikarbutonActionPerformed

    private void firmaeklebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firmaeklebutonActionPerformed
      
         mesajyazisi.setText("");
     javax.swing.table.DefaultTableModel model=(javax.swing.table.DefaultTableModel) firmalartablosu.getModel();
      mesajyazisi.setText("");

      if(firmaadialani.getText().trim().equals(""))
      {
          mesajyazisi.setText("Lutfen bilgileri giriniz!");
      }
      else
      {
          Object[] eklenecek = {firmaadialani.getText(),firmagirisadialani.getText(),firmasifrealani.getText(),hizmetgir.getText()};
          model.addRow(eklenecek);     
      }     
       
        // TODO add your handling code here:

    }//GEN-LAST:event_firmaeklebutonActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
     menu menuyedon = new menu();
     menuyedon.setVisible(true);
     
     this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void firmalartablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firmalartablosuMouseClicked
 javax.swing.table.DefaultTableModel model =(javax.swing.table.DefaultTableModel)firmalartablosu.getModel();
     int secilirow=firmalartablosu.getSelectedRow();
     firmaadialani.setText(model.getValueAt(secilirow,0).toString());
     firmagirisadialani.setText(model.getValueAt(secilirow, 1).toString());
     firmasifrealani.setText(model.getValueAt(secilirow, 2).toString());
      hizmetgir.setText(model.getValueAt(secilirow, 3).toString());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_firmalartablosuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpanel().setVisible(true);
            }
        });
          java.awt.EventQueue.invokeLater(() -> {
            adminpanel admin = new adminpanel();
            admin.setVisible(true);

            // Başlangıçta araçları listele
            admin.firmalarilistele();
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firmaadialani;
    private javax.swing.JButton firmacikarbuton;
    private javax.swing.JButton firmaeklebuton;
    private javax.swing.JTextField firmagirisadialani;
    private javax.swing.JTable firmalartablosu;
    private javax.swing.JTextField firmasifrealani;
    private javax.swing.JTextField hizmetgir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu;
    private javax.swing.JLabel mesajyazisi;
    // End of variables declaration//GEN-END:variables
}
