/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje2.deneme.pkg1;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reyha
 */



public class bilet_al extends javax.swing.JFrame {

    /**
     * Creates new form bilet_al
     */
    public bilet_al() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    class arac_goster
{
        private String firma_Turu ;
        private String arac_Turu;
        
        public arac_goster(String[] firma_Turu,String[] arac_Turu)
        {
            this.firma_Turu = firma_Turu[new Random().nextInt(firma_Turu.length)];
            this.arac_Turu = arac_Turu[new Random().nextInt(arac_Turu.length)];
        }

    public String getFirma_Turu() {
        return firma_Turu;
    }

    public String getArac_Turu() {
        return arac_Turu;
    }

    public void setFirma_Turu(String firma_Turu) {
        this.firma_Turu = firma_Turu;
    }

    public void setArac_Turu(String arac_Turu) {
        this.arac_Turu = arac_Turu;
    }
        
}




private void arac_bul() 
{
    String secilenTarih = (String) tarihcbox.getSelectedItem();

    DefaultTableModel tableModel = (DefaultTableModel) aractablosu.getModel();
    tableModel.setRowCount(0);

    if (secilenTarih.equals("4 Aralik") || secilenTarih.equals("5 Aralik") || secilenTarih.equals("6 Aralik") || secilenTarih.equals("7 Aralik") || secilenTarih.equals("8 Aralik") || secilenTarih.equals("9 Aralik") || secilenTarih.equals("10 Aralik")) 
    {
        int random_AracSayisi = new Random().nextInt(6) + 1;
        String[] firma_Turu = {"A firmasi", "B firmasi", "C firmasi", "D firmasi", "F firmasi"};

        for (int i = 0; i < random_AracSayisi; i++) {
            String[] arac_Turu = null;

            if (firma_Turu[i].equals("A firmasi") || firma_Turu[i].equals("B firmasi")) {
                arac_Turu = new String[]{"otobus 1", "otobus 2"};
            } else if (firma_Turu[i].equals("C firmasi")) {
                arac_Turu = new String[]{"otobus 1", "ucak 1", "ucak 2"};
            } else if (firma_Turu[i].equals("D firmasi")) {
                arac_Turu = new String[]{"tren 1", "tren 2", "tren 3"};
            } else if (firma_Turu[i].equals("F firmasi")) {
                arac_Turu = new String[]{"ucak 1", "ucak 2"};
            }

    arac_goster arac = new arac_goster(new String[]{firma_Turu[i]}, arac_Turu);

            tableModel.addRow(new Object[]{secilenTarih, arac.getFirma_Turu(), arac.getArac_Turu()});
        }
    }
    
}


    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JButton();
        tarihcbox = new javax.swing.JComboBox<>();
        araclarigor = new javax.swing.JButton();
        rezervasyon = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        aractablosu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        menu.setBackground(new java.awt.Color(102, 102, 102));
        menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("menü");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        tarihcbox.setBackground(new java.awt.Color(204, 255, 255));
        tarihcbox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tarihcbox.setForeground(new java.awt.Color(0, 153, 153));
        tarihcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 Aralik", "5 Aralik", "6 Aralik", "7 Aralik", "8 Aralik", "9 Aralik", "10 Aralik" }));

        araclarigor.setBackground(new java.awt.Color(204, 255, 255));
        araclarigor.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        araclarigor.setForeground(new java.awt.Color(0, 153, 153));
        araclarigor.setText("Araçları Görüntüle");
        araclarigor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araclarigorActionPerformed(evt);
            }
        });

        rezervasyon.setBackground(new java.awt.Color(204, 255, 255));
        rezervasyon.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        rezervasyon.setForeground(new java.awt.Color(0, 153, 153));
        rezervasyon.setText("Rezervasyon Yap");
        rezervasyon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rezervasyonActionPerformed(evt);
            }
        });

        aractablosu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        aractablosu.setForeground(new java.awt.Color(0, 153, 153));
        aractablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "GÜN", "FİRMA", "ARAÇ"
            }
        ));
        aractablosu.setGridColor(new java.awt.Color(255, 51, 51));
        aractablosu.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jScrollPane2.setViewportView(aractablosu);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gün İçindeki Bulunan Araçlar : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(rezervasyon, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tarihcbox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(araclarigor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(araclarigor, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(tarihcbox))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(rezervasyon, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
menu menuyegit=new menu();
menuyegit.setVisible(true);

     this.setVisible(false);        

        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void rezervasyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rezervasyonActionPerformed
rezervasyon rezervasyonagit=new rezervasyon();
rezervasyonagit.setVisible(true);

     this.setVisible(false);        

        // TODO add your handling code here:
    }//GEN-LAST:event_rezervasyonActionPerformed

    private void araclarigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araclarigorActionPerformed

        arac_bul();
        // TODO add your handling code here:
    }//GEN-LAST:event_araclarigorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bilet_al.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bilet_al.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bilet_al.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bilet_al.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bilet_al().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton araclarigor;
    private javax.swing.JTable aractablosu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton menu;
    private javax.swing.JButton rezervasyon;
    private javax.swing.JComboBox<String> tarihcbox;
    // End of variables declaration//GEN-END:variables
}
