/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje2.deneme.pkg1;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reyha
 */
public class Cfirma extends javax.swing.JFrame {

    /**
     * Creates new form Cfirma
     */
    public Cfirma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mesajyazisi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cfirmatablo = new javax.swing.JTable();
        cikarbuton = new javax.swing.JButton();
        eklebuton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        sefercbox = new javax.swing.JComboBox<>();
        yakitcbox = new javax.swing.JComboBox<>();
        idyazialani = new javax.swing.JTextField();
        koltukcbox = new javax.swing.JComboBox<>();
        aracyazialani = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        Cfirmatablo.setBackground(new java.awt.Color(102, 102, 102));
        Cfirmatablo.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        Cfirmatablo.setForeground(new java.awt.Color(204, 204, 204));
        Cfirmatablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Otobüs veya Uçak no:", "Koltuk Sayısı", "ID", "Yakıt Türü", "Sefer No"
            }
        ));
        Cfirmatablo.setSelectionBackground(new java.awt.Color(255, 0, 0));
        Cfirmatablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CfirmatabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Cfirmatablo);

        cikarbuton.setBackground(new java.awt.Color(255, 0, 0));
        cikarbuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cikarbuton.setForeground(new java.awt.Color(255, 255, 255));
        cikarbuton.setText("Çıkar");
        cikarbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikarbutonActionPerformed(evt);
            }
        });

        eklebuton.setBackground(new java.awt.Color(102, 255, 0));
        eklebuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eklebuton.setForeground(new java.awt.Color(255, 255, 255));
        eklebuton.setText("Ekle");
        eklebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eklebutonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GERİ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sefercbox.setBackground(new java.awt.Color(102, 102, 102));
        sefercbox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        sefercbox.setForeground(new java.awt.Color(255, 255, 255));
        sefercbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.Sefer", "2.Sefer", "3.Sefer", "4.Sefer", "5.Sefer", "6.Sefer" }));
        sefercbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sefercboxActionPerformed(evt);
            }
        });

        yakitcbox.setBackground(new java.awt.Color(102, 102, 102));
        yakitcbox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        yakitcbox.setForeground(new java.awt.Color(255, 255, 255));
        yakitcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motorin", "Gaz" }));
        yakitcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yakitcboxActionPerformed(evt);
            }
        });

        idyazialani.setBackground(new java.awt.Color(102, 102, 102));
        idyazialani.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        idyazialani.setForeground(new java.awt.Color(255, 255, 255));
        idyazialani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idyazialaniActionPerformed(evt);
            }
        });

        koltukcbox.setBackground(new java.awt.Color(102, 102, 102));
        koltukcbox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltukcbox.setForeground(new java.awt.Color(255, 255, 255));
        koltukcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15", "20", "25", "30" }));
        koltukcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koltukcboxActionPerformed(evt);
            }
        });

        aracyazialani.setBackground(new java.awt.Color(102, 102, 102));
        aracyazialani.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        aracyazialani.setForeground(new java.awt.Color(255, 255, 255));
        aracyazialani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aracyazialaniActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Otobüs No:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Koltuk Sayısı:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Yakıt Türü:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Sefer Türü:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("C FİRMASI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cikarbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(266, 266, 266)
                        .addComponent(eklebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(181, 181, 181))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aracyazialani)
                    .addComponent(sefercbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yakitcbox, 0, 146, Short.MAX_VALUE)
                    .addComponent(idyazialani)
                    .addComponent(koltukcbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(429, 429, 429))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(146, 146, 146)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(aracyazialani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltukcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eklebuton)
                    .addComponent(idyazialani, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(cikarbuton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yakitcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sefercbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(96, 96, 96)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mesajyazisi))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(mesajyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eklebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eklebutonActionPerformed
mesajyazisi.setText("");
      DefaultTableModel model=(DefaultTableModel) Cfirmatablo.getModel();
      mesajyazisi.setText("");

      if(aracyazialani.getText().trim().equals(""))
      {
          mesajyazisi.setText("Lutfen bilgileri giriniz!");
      }
      else
      {
          Object[] eklenecek = {aracyazialani.getText(),koltukcbox.getSelectedItem().toString(),idyazialani.getText(),yakitcbox.getSelectedItem().toString(),sefercbox.getSelectedItem().toString()};
          model.addRow(eklenecek);
      }        // TODO add your handling code here:
    }//GEN-LAST:event_eklebutonActionPerformed

    private void cikarbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikarbutonActionPerformed

mesajyazisi.setText("");
        DefaultTableModel model =(DefaultTableModel)Cfirmatablo.getModel();
     int secilirow=Cfirmatablo.getSelectedRow();
     if(secilirow == -1)
     {  
         if(Cfirmatablo.getRowCount() == 0)
         { 
             mesajyazisi.setText("Tablo su anda bos");
         }
         else
         {
           mesajyazisi.setText("secilecek satir secin");   
         }
         
     }
         
     else
     {
         model.removeRow(secilirow);
         mesajyazisi.setText("urun basariyla silindi");
     }        // TODO add your handling code here:
    }//GEN-LAST:event_cikarbutonActionPerformed

    private void CfirmatabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CfirmatabloMouseClicked

        
        DefaultTableModel model =(DefaultTableModel)Cfirmatablo.getModel();
     int secilirow=Cfirmatablo.getSelectedRow();
     aracyazialani.setText(model.getValueAt(secilirow,0).toString());
     koltukcbox.setSelectedItem(model.getValueAt(secilirow, 1).toString());
     idyazialani.setText(model.getValueAt(secilirow, 2).toString());
     yakitcbox.setSelectedItem(model.getValueAt(secilirow, 3).toString());
     sefercbox.setSelectedItem(model.getValueAt(secilirow,4).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_CfirmatabloMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     firma menuyedon = new firma();
     menuyedon.setVisible(true); 
   
     this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aracyazialaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aracyazialaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aracyazialaniActionPerformed

    private void koltukcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koltukcboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_koltukcboxActionPerformed

    private void idyazialaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idyazialaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idyazialaniActionPerformed

    private void yakitcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yakitcboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yakitcboxActionPerformed

    private void sefercboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sefercboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sefercboxActionPerformed

    /**
     * @param args the command line arguments
     */
    void araclariListele() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Cfirmatablo.getModel();

        // Örnek araçlar ekleyelim (gerçek veritabanından veya başka bir kaynaktan alabilirsiniz)
        Object[] arac1 = {"Otobus1", "20", "123REE", "Motorin", "4.Sefer"};
        Object[] arac2 = {"Ucak1", "30", "456SEE", "gaz", "5.Sefer"};
        Object[] arac3 = {"Ucak2", "30", "789KEE", "gaz", "5.Sefer"};
        // Mevcut tabloya örnek verileri ekle
        model.addRow(arac1);
        model.addRow(arac2);
        model.addRow(arac3);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cfirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cfirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cfirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cfirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cfirma().setVisible(true);
            }
        });
        java.awt.EventQueue.invokeLater(() -> 
        {
            Cfirma afirma = new Cfirma();
            afirma.setVisible(true);

            // Başlangıçta araçları listele
            afirma.araclariListele();
         });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Cfirmatablo;
    private javax.swing.JTextField aracyazialani;
    private javax.swing.JButton cikarbuton;
    private javax.swing.JButton eklebuton;
    private javax.swing.JTextField idyazialani;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> koltukcbox;
    private javax.swing.JLabel mesajyazisi;
    private javax.swing.JComboBox<String> sefercbox;
    private javax.swing.JComboBox<String> yakitcbox;
    // End of variables declaration//GEN-END:variables
}
