/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje2.deneme.pkg1;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reyha
 */
public class Dfirma extends javax.swing.JFrame {

    /**
     * Creates new form Dfirma
     */
    public Dfirma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mesajyazisi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aracyazialani = new javax.swing.JTextField();
        koltukcbox = new javax.swing.JComboBox<>();
        idyazialani = new javax.swing.JTextField();
        yakitcbox = new javax.swing.JComboBox<>();
        sefercbox = new javax.swing.JComboBox<>();
        eklebuton = new javax.swing.JButton();
        cikarbuton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dfirmatablo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GERİ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Tren No:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("koltuk sayısı:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("yakıt türü: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("sefer türü: ");

        aracyazialani.setBackground(new java.awt.Color(153, 153, 153));
        aracyazialani.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        aracyazialani.setForeground(new java.awt.Color(255, 255, 255));
        aracyazialani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aracyazialaniActionPerformed(evt);
            }
        });

        koltukcbox.setBackground(new java.awt.Color(153, 153, 153));
        koltukcbox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltukcbox.setForeground(new java.awt.Color(255, 255, 255));
        koltukcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15", "20", "25", "30" }));
        koltukcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koltukcboxActionPerformed(evt);
            }
        });

        idyazialani.setBackground(new java.awt.Color(153, 153, 153));
        idyazialani.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        idyazialani.setForeground(new java.awt.Color(255, 255, 255));
        idyazialani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idyazialaniActionPerformed(evt);
            }
        });

        yakitcbox.setBackground(new java.awt.Color(153, 153, 153));
        yakitcbox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        yakitcbox.setForeground(new java.awt.Color(255, 255, 255));
        yakitcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elektrik" }));
        yakitcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yakitcboxActionPerformed(evt);
            }
        });

        sefercbox.setBackground(new java.awt.Color(153, 153, 153));
        sefercbox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        sefercbox.setForeground(new java.awt.Color(255, 255, 255));
        sefercbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.Sefer", "2.Sefer", "3.Sefer", "4.Sefer", "5.Sefer", "6.Sefer" }));
        sefercbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sefercboxActionPerformed(evt);
            }
        });

        eklebuton.setBackground(new java.awt.Color(102, 204, 0));
        eklebuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eklebuton.setForeground(new java.awt.Color(255, 255, 255));
        eklebuton.setText("Ekle");
        eklebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eklebutonActionPerformed(evt);
            }
        });

        cikarbuton.setBackground(new java.awt.Color(204, 0, 51));
        cikarbuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cikarbuton.setForeground(new java.awt.Color(255, 255, 255));
        cikarbuton.setText("Çıkar");
        cikarbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikarbutonActionPerformed(evt);
            }
        });

        Dfirmatablo.setBackground(new java.awt.Color(153, 153, 153));
        Dfirmatablo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Dfirmatablo.setForeground(new java.awt.Color(51, 51, 51));
        Dfirmatablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tren No", "Koltuk Sayısı", "ID", "Yakıt Türü", "Sefer No"
            }
        ));
        Dfirmatablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DfirmatabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Dfirmatablo);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("D FİRMASI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eklebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cikarbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yakitcbox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sefercbox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idyazialani, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukcbox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aracyazialani, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(eklebuton)
                        .addGap(39, 39, 39)
                        .addComponent(cikarbuton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aracyazialani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(koltukcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idyazialani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yakitcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sefercbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(mesajyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mesajyazisi))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void araclariListele() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Dfirmatablo.getModel();

        // Örnek araçlar ekleyelim (gerçek veritabanından veya başka bir kaynaktan alabilirsiniz)
        Object[] arac1 = {"Tren1", "25", "1TR", "Elektrik", "1.Sefer"};
        Object[] arac2 = {"Tren2", "25", "2TR", "Elektrik", "2.Sefer"};
        Object[] arac3 = {"Tren3", "25", "3TR", "Elektrik", "2.Sefer"};
        // Mevcut tabloya örnek verileri ekle
        model.addRow(arac1);
        model.addRow(arac2);
        model.addRow(arac3);
}
    private void aracyazialaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aracyazialaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aracyazialaniActionPerformed

    private void yakitcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yakitcboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yakitcboxActionPerformed

    private void eklebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eklebutonActionPerformed
mesajyazisi.setText("");
      DefaultTableModel model=(DefaultTableModel) Dfirmatablo.getModel();
      mesajyazisi.setText("");

      if(aracyazialani.getText().trim().equals(""))
      {
          mesajyazisi.setText("Lutfen bilgileri giriniz!");
      }
      else
      {
          Object[] eklenecek = {aracyazialani.getText(),koltukcbox.getSelectedItem().toString(),idyazialani.getText(),yakitcbox.getSelectedItem().toString(),sefercbox.getSelectedItem().toString()};
          model.addRow(eklenecek);
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_eklebutonActionPerformed

    private void cikarbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikarbutonActionPerformed
mesajyazisi.setText("");
        DefaultTableModel model =(DefaultTableModel)Dfirmatablo.getModel();
     int secilirow=Dfirmatablo.getSelectedRow();
     if(secilirow == -1)
     {  
         if(Dfirmatablo.getRowCount() == 0)
         { 
             mesajyazisi.setText("Tablo su anda bos");
         }
         else
         {
           mesajyazisi.setText("secilecek satir secin");   
         }
         
     }
         
     else
     {
         model.removeRow(secilirow);
         mesajyazisi.setText("urun basariyla silindi");
     }        // TODO add your handling code here:
    }//GEN-LAST:event_cikarbutonActionPerformed

    private void DfirmatabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DfirmatabloMouseClicked

        DefaultTableModel model =(DefaultTableModel)Dfirmatablo.getModel();
     int secilirow=Dfirmatablo.getSelectedRow();
     aracyazialani.setText(model.getValueAt(secilirow,0).toString());
     koltukcbox.setSelectedItem(model.getValueAt(secilirow, 1).toString());
     idyazialani.setText(model.getValueAt(secilirow, 2).toString());
     yakitcbox.setSelectedItem(model.getValueAt(secilirow, 3).toString());
     sefercbox.setSelectedItem(model.getValueAt(secilirow,4).toString());          // TODO add your handling code here:
    }//GEN-LAST:event_DfirmatabloMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     firma menuyedon = new firma();
     menuyedon.setVisible(true);    

    this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void koltukcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koltukcboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_koltukcboxActionPerformed

    private void idyazialaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idyazialaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idyazialaniActionPerformed

    private void sefercboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sefercboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sefercboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dfirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dfirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dfirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dfirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dfirma().setVisible(true);
            }
        });
        java.awt.EventQueue.invokeLater(() -> 
        {
            Dfirma afirma = new Dfirma();
            afirma.setVisible(true);

            // Başlangıçta araçları listele
            afirma.araclariListele();
         });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Dfirmatablo;
    private javax.swing.JTextField aracyazialani;
    private javax.swing.JButton cikarbuton;
    private javax.swing.JButton eklebuton;
    private javax.swing.JTextField idyazialani;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> koltukcbox;
    private javax.swing.JLabel mesajyazisi;
    private javax.swing.JComboBox<String> sefercbox;
    private javax.swing.JComboBox<String> yakitcbox;
    // End of variables declaration//GEN-END:variables
}
