/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje2.deneme.pkg1;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reyha
 */
public class Ffirma extends javax.swing.JFrame {

    /**
     * Creates new form Ffirma
     */
    public Ffirma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mesajyazisi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aracyazialani = new javax.swing.JTextField();
        koltukcbox = new javax.swing.JComboBox<>();
        idyazialani = new javax.swing.JTextField();
        yakitcbox = new javax.swing.JComboBox<>();
        sefercbox = new javax.swing.JComboBox<>();
        eklebuton = new javax.swing.JButton();
        cikarbuton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ffirmatablo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GERİ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("arac no :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("koltuk sayısı: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("yakıt türü:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("sefer türü: ");

        aracyazialani.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        aracyazialani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aracyazialaniActionPerformed(evt);
            }
        });

        koltukcbox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltukcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15", "20", "25", "30" }));
        koltukcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koltukcboxActionPerformed(evt);
            }
        });

        idyazialani.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        idyazialani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idyazialaniActionPerformed(evt);
            }
        });

        yakitcbox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        yakitcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gaz" }));
        yakitcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yakitcboxActionPerformed(evt);
            }
        });

        sefercbox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        sefercbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.Sefer", "2.Sefer", "3.Sefer", "4.Sefer", "5.Sefer", "6.Sefer" }));
        sefercbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sefercboxActionPerformed(evt);
            }
        });

        eklebuton.setBackground(new java.awt.Color(51, 153, 0));
        eklebuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eklebuton.setForeground(new java.awt.Color(255, 255, 255));
        eklebuton.setText("Ekle");
        eklebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eklebutonActionPerformed(evt);
            }
        });

        cikarbuton.setBackground(new java.awt.Color(204, 0, 0));
        cikarbuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cikarbuton.setForeground(new java.awt.Color(255, 255, 255));
        cikarbuton.setText("Çıkar");
        cikarbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikarbutonActionPerformed(evt);
            }
        });

        Ffirmatablo.setBackground(new java.awt.Color(102, 102, 102));
        Ffirmatablo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Ffirmatablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Uçak No", "Koltuk Sayısı", "ID", "Yakıt Türü", "Sefer No"
            }
        ));
        Ffirmatablo.setGridColor(new java.awt.Color(255, 255, 255));
        Ffirmatablo.setSelectionBackground(new java.awt.Color(102, 102, 102));
        Ffirmatablo.setSelectionForeground(new java.awt.Color(255, 0, 0));
        Ffirmatablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FfirmatabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Ffirmatablo);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("F FİRMASI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(aracyazialani, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yakitcbox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sefercbox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idyazialani, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(koltukcbox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eklebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cikarbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(aracyazialani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(eklebuton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(koltukcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idyazialani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(cikarbuton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yakitcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sefercbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mesajyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesajyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eklebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eklebutonActionPerformed
mesajyazisi.setText("");
      DefaultTableModel model=(DefaultTableModel) Ffirmatablo.getModel();
      mesajyazisi.setText("");

      if(aracyazialani.getText().trim().equals(""))
      {
          mesajyazisi.setText("Lutfen bilgileri giriniz!");
      }
      else
      {
          Object[] eklenecek = {aracyazialani.getText(),koltukcbox.getSelectedItem().toString(),idyazialani.getText(),yakitcbox.getSelectedItem().toString(),sefercbox.getSelectedItem().toString()};
          model.addRow(eklenecek);
      }        // TODO add your handling code here:
    }//GEN-LAST:event_eklebutonActionPerformed

    private void cikarbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikarbutonActionPerformed
mesajyazisi.setText("");
        DefaultTableModel model =(DefaultTableModel)Ffirmatablo.getModel();
     int secilirow=Ffirmatablo.getSelectedRow();
     if(secilirow == -1)
     {  
         if(Ffirmatablo.getRowCount() == 0)
         { 
             mesajyazisi.setText("Tablo su anda bos");
         }
         else
         {
           mesajyazisi.setText("secilecek satir secin");   
         }
         
     }
         
     else
     {
         model.removeRow(secilirow);
         mesajyazisi.setText("urun basariyla silindi");
     }        // TODO add your handling code here:
    }//GEN-LAST:event_cikarbutonActionPerformed

    private void FfirmatabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FfirmatabloMouseClicked

        DefaultTableModel model =(DefaultTableModel)Ffirmatablo.getModel();
     int secilirow=Ffirmatablo.getSelectedRow();
     aracyazialani.setText(model.getValueAt(secilirow,0).toString());
     koltukcbox.setSelectedItem(model.getValueAt(secilirow, 1).toString());
     idyazialani.setText(model.getValueAt(secilirow, 2).toString());
     yakitcbox.setSelectedItem(model.getValueAt(secilirow, 3).toString());
     sefercbox.setSelectedItem(model.getValueAt(secilirow,4).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_FfirmatabloMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    firma menuyedon = new firma();
     menuyedon.setVisible(true); 

     this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aracyazialaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aracyazialaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aracyazialaniActionPerformed

    private void koltukcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koltukcboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_koltukcboxActionPerformed

    private void idyazialaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idyazialaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idyazialaniActionPerformed

    private void yakitcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yakitcboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yakitcboxActionPerformed

    private void sefercboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sefercboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sefercboxActionPerformed

    /**
     * @param args the command line arguments
     */
    void araclariListele() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Ffirmatablo.getModel();

        // Örnek araçlar ekleyelim (gerçek veritabanından veya başka bir kaynaktan alabilirsiniz)
        Object[] arac1 = {"Ucak1", "30", "1UC", "gaz", "6.Sefer"};
        Object[] arac2 = {"Ucak2", "30", "2UC", "gaz", "6.Sefer"};  
        // Mevcut tabloya örnek verileri ekle
        model.addRow(arac1);
        model.addRow(arac2);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ffirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ffirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ffirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ffirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ffirma().setVisible(true);
            }
        });
        java.awt.EventQueue.invokeLater(() -> 
        {
            Ffirma afirma = new Ffirma();
            afirma.setVisible(true);

            // Başlangıçta araçları listele
            afirma.araclariListele();
         });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ffirmatablo;
    private javax.swing.JTextField aracyazialani;
    private javax.swing.JButton cikarbuton;
    private javax.swing.JButton eklebuton;
    private javax.swing.JTextField idyazialani;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> koltukcbox;
    private javax.swing.JLabel mesajyazisi;
    private javax.swing.JComboBox<String> sefercbox;
    private javax.swing.JComboBox<String> yakitcbox;
    // End of variables declaration//GEN-END:variables
}
