/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje2.deneme.pkg1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author reyha
 */
class User{

private String kullaniciadi;
private String parola;

    public String getKullaniciadi() {
        return kullaniciadi;
    }

    public void setKullaniciadi(String kullaniciadi) {
        this.kullaniciadi = kullaniciadi;
    }

    public String getParola() {
        return parola;
    }

    public void setParola(String parola) {
        this.parola = parola;
    }

    public User(String kullaniciadi, String parola) {
        this.kullaniciadi = kullaniciadi;
        this.parola = parola;
}

}
public class firmagirisi extends javax.swing.JFrame {
static ArrayList<User> userlist= new ArrayList<User>();

    public static ArrayList<User> getUserlist() {
        return userlist;
    }

    public static void setUserlist(ArrayList<User> userlist) {
        firmagirisi.userlist =userlist;
}
    /**
     * Creates new form firmagirisi
     */
    public firmagirisi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        geributon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kullaniciadialani = new javax.swing.JTextField();
        sifrealani = new javax.swing.JPasswordField();
        girisbuton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        geributon.setBackground(new java.awt.Color(153, 153, 153));
        geributon.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        geributon.setForeground(new java.awt.Color(255, 255, 255));
        geributon.setText("GERİ");
        geributon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geributonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Firma Kullanıcı Adı:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Firma Şifre:");

        kullaniciadialani.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        sifrealani.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        girisbuton.setBackground(new java.awt.Color(153, 153, 153));
        girisbuton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        girisbuton.setForeground(new java.awt.Color(255, 255, 255));
        girisbuton.setText("giris yap");
        girisbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisbutonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("**firmanızın kullanıcı bilgilerini giriniz**");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(geributon)
                                    .addGap(107, 107, 107)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kullaniciadialani)
                            .addComponent(sifrealani, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                        .addContainerGap(140, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(girisbuton)
                                .addGap(154, 154, 154))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(geributon)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullaniciadialani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifrealani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(51, 51, 51)
                .addComponent(girisbuton)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void girisbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisbutonActionPerformed
String kullaniciadi=kullaniciadialani.getText();
        String parola= new String(sifrealani.getPassword());
      String message = null;
      if(kullaniciadi.equals("firmaA"))
      {
          if(kullaniciadi.equals("firmaA") && parola.equals("123"))
      { 
          Afirma afirma = new Afirma();
          afirma.setVisible(true);
          
          this.setVisible(false);
          afirma.araclariListele();
          message="hosgeldiniz "+ kullaniciadi;
       }
      else  if(kullaniciadi.equals("firmaA") && !parola.equals("123"))
      { 
          message="parola hatali";
       }
      else  if(!kullaniciadi.equals("firmaA") && parola.equals("123"))
      { 
          message="kullanici adi hatali";
       }
      else  if(!kullaniciadi.equals("firmaA") && !parola.equals("123"))
      { 
          message="parola ve kullanici adi hatali";
       }
      JOptionPane.showMessageDialog(this, message);
      }
      
      
      if(kullaniciadi.equals("firmaB"))
      { 
           if(kullaniciadi.equals("firmaB") && parola.equals("1234"))
      { 
           Bfirma bfirma = new Bfirma();
          bfirma.setVisible(true);
          
           this.setVisible(false);
          bfirma.araclariListele();
          message="hosgeldiniz "+ kullaniciadi;
       }
      else  if(kullaniciadi.equals("firmaB") && !parola.equals("1234"))
      { 
          message="parola hatali";
       }
      else  if(!kullaniciadi.equals("firmaB") && parola.equals("1234"))
      { 
          message="kullanici adi hatali";
       }
      else  if(!kullaniciadi.equals("firmaB") && !parola.equals("1234"))
      { 
          message="parola ve kullanici adi hatali";
       }
      JOptionPane.showMessageDialog(this, message);
      
      }
      
     
      if(kullaniciadi.equals("firmaC"))
      {
          if(kullaniciadi.equals("firmaC") && parola.equals("12345"))
      { 
           Cfirma cfirma = new Cfirma();
          cfirma.setVisible(true);
          
           this.setVisible(false);
          cfirma.araclariListele();
          message="hosgeldiniz "+ kullaniciadi;
       }
      else  if(kullaniciadi.equals("firmaC") && !parola.equals("12345"))
      { 
          message="parola hatali";
       }
      else  if(!kullaniciadi.equals("firmaC") && parola.equals("12345"))
      { 
          message="kullanici adi hatali";
       }
      else  if(!kullaniciadi.equals("firmaC") && !parola.equals("12345"))
      { 
          message="parola ve kullanici adi hatali";
       }
      JOptionPane.showMessageDialog(this, message);
      
      }
      
      
      
      
      if(kullaniciadi.equals("firmaD"))
      {
      if(kullaniciadi.equals("firmaD") && parola.equals("123456"))
      { 
           Dfirma dfirma = new Dfirma();
          dfirma.setVisible(true);
          
           this.setVisible(false);
          dfirma.araclariListele();
          message="hosgeldiniz "+ kullaniciadi;
       }
      else  if(kullaniciadi.equals("firmaD") && !parola.equals("123456"))
      { 
          message="parola hatali";
       }
      else  if(!kullaniciadi.equals("firmaD") && parola.equals("123456"))
      { 
          message="kullanici adi hatali";
       }
      else  if(!kullaniciadi.equals("firmaD") && !parola.equals("123456"))
      { 
          message="parola ve kullanici adi hatali";
       }
      JOptionPane.showMessageDialog(this, message);
      }
      
      
      
      if(kullaniciadi.equals("firmaF"))
      {
           if(kullaniciadi.equals("firmaF") && parola.equals("1234567"))
      { 
           Ffirma ffirma = new Ffirma();
          ffirma.setVisible(true);
          
           this.setVisible(false);
          ffirma.araclariListele();
          message="hosgeldiniz "+ kullaniciadi;
       }
      else  if(kullaniciadi.equals("firmaF") && !parola.equals("1234567"))
      { 
          message="parola hatali";
       }
      else  if(!kullaniciadi.equals("firmaF") && parola.equals("1234567"))
      { 
          message="kullanici adi hatali";
       }
      else  if(!kullaniciadi.equals("firmaF") && !parola.equals("1234567"))
      { 
          message="parola ve kullanici adi hatali";
       }
      JOptionPane.showMessageDialog(this, message);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_girisbutonActionPerformed

    private void geributonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geributonActionPerformed
      firma geri= new firma();
      geri.setVisible(true);
      
      this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_geributonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firmagirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firmagirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firmagirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firmagirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firmagirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton geributon;
    private javax.swing.JButton girisbuton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kullaniciadialani;
    private javax.swing.JPasswordField sifrealani;
    // End of variables declaration//GEN-END:variables
}
