/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje2.deneme.pkg1;


import java.util.LinkedHashSet;
import java.util.Random;
import java.util.Set;
import javax.swing.JCheckBox;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

/**
 *
 * @author reyha
 */
public class koltuk_sayisi15 extends javax.swing.JFrame {
    Set<String> set = new LinkedHashSet<String>();
    
    
    
    private void initRandomlyOccupiedSeats() {
        Random random = new Random();
        int totalSeats = 15; // Toplam koltuk sayısı
        int occupiedSeatCount = 7; // Dolu olacak koltuk sayısı

        for (int i = 0; i < occupiedSeatCount; i++) {
            int randomSeat = random.nextInt(totalSeats) + 1; // Rastgele bir koltuk seç
            set.add(Integer.toString(randomSeat));
        }
    

        label_dolu();
    }
    
    public koltuk_sayisi15() {
        initComponents();
        initRandomlyOccupiedSeats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        sofor_koltugu = new javax.swing.JLabel();
        koltuk1 = new javax.swing.JCheckBox();
        koltuk2 = new javax.swing.JCheckBox();
        koltuk3 = new javax.swing.JCheckBox();
        koltuk4 = new javax.swing.JCheckBox();
        koltuk5 = new javax.swing.JCheckBox();
        koltuk6 = new javax.swing.JCheckBox();
        koltuk7 = new javax.swing.JCheckBox();
        koltuk8 = new javax.swing.JCheckBox();
        koltuk9 = new javax.swing.JCheckBox();
        koltuk10 = new javax.swing.JCheckBox();
        koltuk11 = new javax.swing.JCheckBox();
        koltuk12 = new javax.swing.JCheckBox();
        koltuk13 = new javax.swing.JCheckBox();
        koltuk14 = new javax.swing.JCheckBox();
        koltuk15 = new javax.swing.JCheckBox();
        goster = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        secilen_koltuklar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dolu_koltuklar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fiyatgoster = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        geributon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        sofor_koltugu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        sofor_koltugu.setForeground(new java.awt.Color(255, 255, 255));
        sofor_koltugu.setText("Şoför koltuğu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sofor_koltugu)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(sofor_koltugu)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        koltuk1.setText("1");

        koltuk2.setText("2");

        koltuk3.setText("3");

        koltuk4.setText("4");

        koltuk5.setText("5");

        koltuk6.setText("6");

        koltuk7.setText("7");

        koltuk8.setText("8");

        koltuk9.setText("9");

        koltuk10.setText("10");

        koltuk11.setText("11");

        koltuk12.setText("12");

        koltuk13.setText("13");

        koltuk14.setText("14");

        koltuk15.setText("15");

        goster.setBackground(new java.awt.Color(0, 153, 153));
        goster.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        goster.setForeground(new java.awt.Color(255, 255, 255));
        goster.setText("goster");
        goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(koltuk7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(koltuk6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(koltuk5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(koltuk4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(koltuk3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(koltuk2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(koltuk1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(koltuk8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(koltuk15, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(goster))
                            .addComponent(koltuk9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk13, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(koltuk1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk2)
                    .addComponent(koltuk9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk3)
                    .addComponent(koltuk10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk4)
                    .addComponent(koltuk11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk5)
                    .addComponent(koltuk12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk6)
                    .addComponent(koltuk13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk7)
                    .addComponent(koltuk14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk8)
                    .addComponent(koltuk15)
                    .addComponent(goster))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        secilen_koltuklar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        secilen_koltuklar.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("secilen koltuklar :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dolu Koltuklar  :");

        dolu_koltuklar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        dolu_koltuklar.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dolu_koltuklar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secilen_koltuklar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dolu_koltuklar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secilen_koltuklar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 204, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ödenecek Tutar:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiyatgoster, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(fiyatgoster, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(0, 204, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Onayla ve Devam Et");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        geributon.setBackground(new java.awt.Color(0, 204, 102));
        geributon.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        geributon.setForeground(new java.awt.Color(255, 255, 255));
        geributon.setText("GERİ");
        geributon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geributonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(geributon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(geributon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void label_degistir()
    {
        String yazi =" ";
        for(String koltuk : set)
        {
            yazi+= koltuk +"  ";
            
        }
        secilen_koltuklar.setText(yazi);
    }
    
    public void label_dolu()
    {
        String yazi2 =" ";
        for(String dolukoltuk : set)
        {
            yazi2 += dolukoltuk + "  ";
        }
        dolu_koltuklar.setText(yazi2);
    }
    
    private JCheckBox getCheckBoxBySeatNumber(int koltuk_numarasi)
    {
        switch(koltuk_numarasi)
        {
            case 1: return koltuk1;
            case 2: return koltuk2;
            case 3: return koltuk3;
            case 4: return koltuk4;
            case 5: return koltuk5;
            case 6: return koltuk6;
            case 7: return koltuk7;
            case 8: return koltuk8;
            case 9: return koltuk9;
            case 10: return koltuk10;
            case 11: return koltuk11;
            case 12: return koltuk12;
            case 13: return koltuk13;
            case 14: return koltuk14;
            case 15: return koltuk15;
            default: return null;
        }
    }
    
    private void gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gosterActionPerformed
        
        java.util.List<String> secili_koltuklar = new java.util.ArrayList<>();
                

        for(int i=1; i<=15; i++)
        {
            JCheckBox kontrol_kutusu = getCheckBoxBySeatNumber(i);
            
            if(kontrol_kutusu.isSelected())
            {
                String secili_koltuk = Integer.toString(i);
                if(set.contains(secili_koltuk))
                {
                    secili_koltuklar.add(secili_koltuk);                }
                else
                {
                    set.add(secili_koltuk);
                }                            
            } 
            else
            {
                set.remove(Integer.toString(i));
            }
                
        }
        
        if (!secili_koltuklar.isEmpty()) 
        {
            StringBuilder message = new StringBuilder();
            message.append("Aşağıdaki koltuklar doludur. Başka bir koltuk seçiniz:\n");
        
           for (String uyari : secili_koltuklar) 
           {
                message.append(uyari).append("\n");
           }

           javax.swing.JOptionPane.showMessageDialog(this, message.toString());
           return; // Uyarı gösterildiyse işlemi sonlandır
        }
        
         if(koltuk1.isSelected())
        {
            set.add("1");
        }
        else
        {
            set.remove("1");
        }
        if(koltuk2.isSelected())
        {
            set.add("2");
        }
        else
        {
            set.remove("2");
        }
        if(koltuk3.isSelected())
        {
            set.add("3");
        }
        else
        {
            set.remove("3");
        }
        if(koltuk4.isSelected())
        {
            set.add("4");
        }
        else
        {
            set.remove("4");
        }
        if(koltuk5.isSelected())
        {
            set.add("5");
        }
        else
        {
            set.remove("5");
        }
        if(koltuk6.isSelected())
        {
            set.add("6");
        }
        else
        {
            set.remove("6");
        }
        if(koltuk7.isSelected())
        {
            set.add("7");
        }
        else
        {
            set.remove("7");
        }
        if(koltuk8.isSelected())
        {
            set.add("8");
        }
        else
        {
            set.remove("8");
        }
        if(koltuk9.isSelected())
        {
            set.add("9");
        }
        else
        {
            set.remove("9");
        }
        if(koltuk10.isSelected())
        {
            set.add("10");
        }
        else
        {
            set.remove("10");
        }
        if(koltuk11.isSelected())
        {
            set.add("11");
        }
        else
        {
            set.remove("11");
        }
        if(koltuk12.isSelected())
        {
            set.add("12");
        }
        else
        {
            set.remove("12");
        }
        if(koltuk13.isSelected())
        {
            set.add("13");
        }
        else
        {
            set.remove("13");
        }
        if(koltuk14.isSelected())
        {
            set.add("14");
        }
        else
        {
            set.remove("14");
        }
        if(koltuk15.isSelected())
        {
            set.add("15");
        }
        else
        {
            set.remove("15");
        }
        
            KoltukBilgileri.setSeciliKoltuklar(secili_koltuklar);

        
        label_degistir();
        
        
    }//GEN-LAST:event_gosterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 yolcubilgileri yolcu=new yolcubilgileri();
        yolcu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void geributonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geributonActionPerformed
        rezervasyon geri = new rezervasyon();
        geri.setVisible(true);
        
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_geributonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(koltuk_sayisi15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(koltuk_sayisi15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(koltuk_sayisi15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(koltuk_sayisi15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new koltuk_sayisi15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dolu_koltuklar;
    private javax.swing.JLabel fiyatgoster;
    private javax.swing.JButton geributon;
    private javax.swing.JButton goster;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JCheckBox koltuk1;
    private javax.swing.JCheckBox koltuk10;
    private javax.swing.JCheckBox koltuk11;
    private javax.swing.JCheckBox koltuk12;
    private javax.swing.JCheckBox koltuk13;
    private javax.swing.JCheckBox koltuk14;
    private javax.swing.JCheckBox koltuk15;
    private javax.swing.JCheckBox koltuk2;
    private javax.swing.JCheckBox koltuk3;
    private javax.swing.JCheckBox koltuk4;
    private javax.swing.JCheckBox koltuk5;
    private javax.swing.JCheckBox koltuk6;
    private javax.swing.JCheckBox koltuk7;
    private javax.swing.JCheckBox koltuk8;
    private javax.swing.JCheckBox koltuk9;
    private javax.swing.JLabel secilen_koltuklar;
    private javax.swing.JLabel sofor_koltugu;
    // End of variables declaration//GEN-END:variables
}
