/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje2.deneme.pkg1;

import java.awt.List;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Random;
import java.util.Set;
import javax.swing.JCheckBox;

/**
 *
 * @author reyha
 */
public class koltuk_sayisi30 extends javax.swing.JFrame {
     Set<String> set = new LinkedHashSet<String>();
     
    
     
     private void initRandomlyOccupiedSeats() {
        Random random = new Random();
        int totalSeats = 30; // Toplam koltuk sayısı
        int occupiedSeatCount = 10; // Dolu olacak koltuk sayısı

        for (int i = 0; i < occupiedSeatCount; i++) {
            int randomSeat = random.nextInt(totalSeats) + 1; // Rastgele bir koltuk seç
            set.add(Integer.toString(randomSeat));
        }

        label_dolu();
    }
     
    public koltuk_sayisi30() {
        initComponents();
        initRandomlyOccupiedSeats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        sofor_koltugu = new javax.swing.JLabel();
        koltuk1 = new javax.swing.JCheckBox();
        koltuk2 = new javax.swing.JCheckBox();
        koltuk3 = new javax.swing.JCheckBox();
        koltuk4 = new javax.swing.JCheckBox();
        koltuk5 = new javax.swing.JCheckBox();
        koltuk6 = new javax.swing.JCheckBox();
        koltuk7 = new javax.swing.JCheckBox();
        koltuk8 = new javax.swing.JCheckBox();
        koltuk9 = new javax.swing.JCheckBox();
        koltuk10 = new javax.swing.JCheckBox();
        koltuk11 = new javax.swing.JCheckBox();
        koltuk12 = new javax.swing.JCheckBox();
        koltuk13 = new javax.swing.JCheckBox();
        koltuk14 = new javax.swing.JCheckBox();
        koltuk15 = new javax.swing.JCheckBox();
        koltuk16 = new javax.swing.JCheckBox();
        koltuk17 = new javax.swing.JCheckBox();
        koltuk18 = new javax.swing.JCheckBox();
        koltuk19 = new javax.swing.JCheckBox();
        koltuk20 = new javax.swing.JCheckBox();
        koltuk21 = new javax.swing.JCheckBox();
        koltuk22 = new javax.swing.JCheckBox();
        koltuk23 = new javax.swing.JCheckBox();
        koltuk24 = new javax.swing.JCheckBox();
        koltuk25 = new javax.swing.JCheckBox();
        koltuk26 = new javax.swing.JCheckBox();
        koltuk27 = new javax.swing.JCheckBox();
        koltuk28 = new javax.swing.JCheckBox();
        koltuk29 = new javax.swing.JCheckBox();
        koltuk30 = new javax.swing.JCheckBox();
        goster = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        secilen_koltuklar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dolu_koltuklar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fiyatgoster = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        geributon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));

        sofor_koltugu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        sofor_koltugu.setForeground(new java.awt.Color(255, 255, 255));
        sofor_koltugu.setText("Şoför koltuğu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sofor_koltugu, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sofor_koltugu, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        koltuk1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk1.setForeground(new java.awt.Color(255, 255, 255));
        koltuk1.setText("1");

        koltuk2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk2.setForeground(new java.awt.Color(255, 255, 255));
        koltuk2.setText("2");

        koltuk3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk3.setForeground(new java.awt.Color(255, 255, 255));
        koltuk3.setText("3");

        koltuk4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk4.setForeground(new java.awt.Color(255, 255, 255));
        koltuk4.setText("4");

        koltuk5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk5.setForeground(new java.awt.Color(255, 255, 255));
        koltuk5.setText("5");

        koltuk6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk6.setForeground(new java.awt.Color(255, 255, 255));
        koltuk6.setText("6");

        koltuk7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk7.setForeground(new java.awt.Color(255, 255, 255));
        koltuk7.setText("7");

        koltuk8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk8.setForeground(new java.awt.Color(255, 255, 255));
        koltuk8.setText("8");

        koltuk9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk9.setForeground(new java.awt.Color(255, 255, 255));
        koltuk9.setText("9");

        koltuk10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk10.setForeground(new java.awt.Color(255, 255, 255));
        koltuk10.setText("10");

        koltuk11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk11.setForeground(new java.awt.Color(255, 255, 255));
        koltuk11.setText("11");

        koltuk12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk12.setForeground(new java.awt.Color(255, 255, 255));
        koltuk12.setText("12");

        koltuk13.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk13.setForeground(new java.awt.Color(255, 255, 255));
        koltuk13.setText("13");

        koltuk14.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk14.setForeground(new java.awt.Color(255, 255, 255));
        koltuk14.setText("14");

        koltuk15.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk15.setForeground(new java.awt.Color(255, 255, 255));
        koltuk15.setText("15");

        koltuk16.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk16.setForeground(new java.awt.Color(255, 255, 255));
        koltuk16.setText("16");

        koltuk17.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk17.setForeground(new java.awt.Color(255, 255, 255));
        koltuk17.setText("17");

        koltuk18.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk18.setForeground(new java.awt.Color(255, 255, 255));
        koltuk18.setText("18");

        koltuk19.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk19.setForeground(new java.awt.Color(255, 255, 255));
        koltuk19.setText("19");

        koltuk20.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk20.setForeground(new java.awt.Color(255, 255, 255));
        koltuk20.setText("20");

        koltuk21.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk21.setForeground(new java.awt.Color(255, 255, 255));
        koltuk21.setText("21");

        koltuk22.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk22.setForeground(new java.awt.Color(255, 255, 255));
        koltuk22.setText("22");

        koltuk23.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk23.setForeground(new java.awt.Color(255, 255, 255));
        koltuk23.setText("23");

        koltuk24.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk24.setForeground(new java.awt.Color(255, 255, 255));
        koltuk24.setText("24");

        koltuk25.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk25.setForeground(new java.awt.Color(255, 255, 255));
        koltuk25.setText("25");

        koltuk26.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk26.setForeground(new java.awt.Color(255, 255, 255));
        koltuk26.setText("26");

        koltuk27.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk27.setForeground(new java.awt.Color(255, 255, 255));
        koltuk27.setText("27");

        koltuk28.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk28.setForeground(new java.awt.Color(255, 255, 255));
        koltuk28.setText("28");

        koltuk29.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk29.setForeground(new java.awt.Color(255, 255, 255));
        koltuk29.setText("29");

        koltuk30.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        koltuk30.setForeground(new java.awt.Color(255, 255, 255));
        koltuk30.setText("30");

        goster.setBackground(new java.awt.Color(102, 0, 102));
        goster.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        goster.setForeground(new java.awt.Color(255, 255, 255));
        goster.setText("göster");
        goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(koltuk15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(koltuk1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(koltuk16, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk17, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk18, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk19, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk20, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk21, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk22, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk23, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk24, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk25, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk26, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk27, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk28, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(koltuk29, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(goster))
                            .addComponent(koltuk30, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 25, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk1)
                    .addComponent(koltuk16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk2)
                    .addComponent(koltuk17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk3)
                    .addComponent(koltuk18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk4)
                    .addComponent(koltuk19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk5)
                    .addComponent(koltuk20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk6)
                    .addComponent(koltuk21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk7)
                    .addComponent(koltuk22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk8)
                    .addComponent(koltuk23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk9)
                    .addComponent(koltuk24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk10)
                    .addComponent(koltuk25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk11)
                    .addComponent(koltuk26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk12)
                    .addComponent(koltuk27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk13)
                    .addComponent(koltuk28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk14)
                    .addComponent(koltuk29)
                    .addComponent(goster))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltuk15)
                    .addComponent(koltuk30))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Secilen Koltuklar :");

        secilen_koltuklar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        secilen_koltuklar.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dolu Koltuklar : ");

        dolu_koltuklar.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        dolu_koltuklar.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(secilen_koltuklar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addComponent(dolu_koltuklar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dolu_koltuklar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secilen_koltuklar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel5.setBackground(new java.awt.Color(204, 0, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ödenecek Tutar:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiyatgoster, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(fiyatgoster, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Onayla ve Devam Et");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        geributon.setBackground(new java.awt.Color(204, 0, 204));
        geributon.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        geributon.setForeground(new java.awt.Color(255, 255, 255));
        geributon.setText("GERİ");
        geributon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geributonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(geributon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(geributon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void label_degistir()
    {
        String yazi =" ";
        for(String koltuk : set)
        {
            yazi+= koltuk +"  ";
            
        }
        secilen_koltuklar.setText(yazi);
    }
    
    public void label_dolu()
    {
        String yazi2 =" ";
        for(String dolukoltuk : set)
        {
            yazi2 += dolukoltuk + "  ";
        }
        dolu_koltuklar.setText(yazi2);
    }
    
    private JCheckBox getCheckBoxBySeatNumber(int koltuk_numarasi)
    {
        switch(koltuk_numarasi)
        {
            case 1: return koltuk1;
            case 2: return koltuk2;
            case 3: return koltuk3;
            case 4: return koltuk4;
            case 5: return koltuk5;
            case 6: return koltuk6;
            case 7: return koltuk7;
            case 8: return koltuk8;
            case 9: return koltuk9;
            case 10: return koltuk10;
            case 11: return koltuk11;
            case 12: return koltuk12;
            case 13: return koltuk13;
            case 14: return koltuk14;
            case 15: return koltuk15;
            case 16: return koltuk16;
            case 17: return koltuk17;
            case 18: return koltuk18;
            case 19: return koltuk19;
            case 20: return koltuk20;
            case 21: return koltuk21;
            case 22: return koltuk22;
            case 23: return koltuk23;
            case 24: return koltuk24;
            case 25: return koltuk25;
            case 26: return koltuk26;
            case 27: return koltuk27;
            case 28: return koltuk28;
            case 29: return koltuk29;
            case 30: return koltuk30;
            default: return null;
        }
    }
    
    private void gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gosterActionPerformed
       
       java.util.List<String> secili_koltuklar = new java.util.ArrayList<>();
        for(int i=1; i<=30; i++)
        {
            JCheckBox kontrol_kutusu = getCheckBoxBySeatNumber(i);
            
            if(kontrol_kutusu.isSelected())
            {
                String secili_koltuk = Integer.toString(i);
                if(set.contains(secili_koltuk))
                {
                    secili_koltuklar.add(secili_koltuk);
                }
                else
                {
                    set.add(secili_koltuk);
                }                            
            } 
            else
            {
                set.remove(Integer.toString(i));
            }
                
        }
        
        if (!secili_koltuklar.isEmpty()) 
        {
            StringBuilder message = new StringBuilder();
            message.append("Aşağıdaki koltuklar doludur. Başka bir koltuk seçiniz:\n");
        
           for (String dolu_koltuk : secili_koltuklar) 
           {
                message.append(dolu_koltuk).append(". koltuk\n");
           }

           javax.swing.JOptionPane.showMessageDialog(this, message.toString());
           return; // Uyarı gösterildiyse işlemi sonlandır
        }
        
        if(koltuk1.isSelected())
        {
            set.add("1");
        }
        else
        {
            set.remove("1");
        }
        if(koltuk2.isSelected())
        {
            set.add("2");
        }
        else
        {
            set.remove("2");
        }
        if(koltuk3.isSelected())
        {
            set.add("3");
        }
        else
        {
            set.remove("3");
        }
        if(koltuk4.isSelected())
        {
            set.add("4");
        }
        else
        {
            set.remove("4");
        }
        if(koltuk5.isSelected())
        {
            set.add("5");
        }
        else
        {
            set.remove("5");
        }
        if(koltuk6.isSelected())
        {
            set.add("6");
        }
        else
        {
            set.remove("6");
        }
        if(koltuk7.isSelected())
        {
            set.add("7");
        }
        else
        {
            set.remove("7");
        }
        if(koltuk8.isSelected())
        {
            set.add("8");
        }
        else
        {
            set.remove("8");
        }
        if(koltuk9.isSelected())
        {
            set.add("9");
        }
        else
        {
            set.remove("9");
        }
        if(koltuk10.isSelected())
        {
            set.add("10");
        }
        else
        {
            set.remove("10");
        }
        if(koltuk11.isSelected())
        {
            set.add("11");
        }
        else
        {
            set.remove("11");
        }
        if(koltuk12.isSelected())
        {
            set.add("12");
        }
        else
        {
            set.remove("12");
        }
        if(koltuk13.isSelected())
        {
            set.add("13");
        }
        else
        {
            set.remove("13");
        }
        if(koltuk14.isSelected())
        {
            set.add("14");
        }
        else
        {
            set.remove("14");
        }
        if(koltuk15.isSelected())
        {
            set.add("15");
        }
        else
        {
            set.remove("15");
        }
        if(koltuk16.isSelected())
        {
            set.add("16");
        }
        else
        {
            set.remove("16");
        }
        if(koltuk17.isSelected())
        {
            set.add("17");
        }
        else
        {
            set.remove("17");
        }
        if(koltuk18.isSelected())
        {
            set.add("18");
        }
        else
        {
            set.remove("18");
        }
        if(koltuk19.isSelected())
        {
            set.add("19");
        }
        else
        {
            set.remove("19");
        }
        if(koltuk20.isSelected())
        {
            set.add("20");
        }
        else
        {
            set.remove("20");
        }
        if(koltuk21.isSelected())
        {
            set.add("21");
        }
        else
        {
            set.remove("21");
        }
        if(koltuk22.isSelected())
        {
            set.add("22");
        }
        else
        {
            set.remove("22");
        }
        if(koltuk23.isSelected())
        {
            set.add("23");
        }
        else
        {
            set.remove("23");
        }
        if(koltuk24.isSelected())
        {
            set.add("24");
        }
        else
        {
            set.remove("24");
        }
        if(koltuk25.isSelected())
        {
            set.add("25");
        }
        else
        {
            set.remove("25");
        }
        if(koltuk26.isSelected())
        {
            set.add("26");
        }
        else
        {
            set.remove("26");
        }
        if(koltuk27.isSelected())
        {
            set.add("27");
        }
        else
        {
            set.remove("27");
        }
        if(koltuk28.isSelected())
        {
            set.add("28");
        }
        else
        {
            set.remove("28");
        }
        if(koltuk29.isSelected())
        {
            set.add("29");
        }
        else
        {
            set.remove("29");
        }
        if(koltuk30.isSelected())
        {
            set.add("30");
        }
        else
        {
            set.remove("30");
        }
        
            KoltukBilgileri.setSeciliKoltuklar(secili_koltuklar);

        
        label_degistir();
    }//GEN-LAST:event_gosterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 yolcubilgileri yolcu=new yolcubilgileri();
        yolcu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void geributonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geributonActionPerformed
     rezervasyon geri = new rezervasyon();
     geri.setVisible(true);
     
     this.setVisible(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_geributonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(koltuk_sayisi30.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(koltuk_sayisi30.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(koltuk_sayisi30.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(koltuk_sayisi30.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new koltuk_sayisi30().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dolu_koltuklar;
    private javax.swing.JLabel fiyatgoster;
    private javax.swing.JButton geributon;
    private javax.swing.JButton goster;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JCheckBox koltuk1;
    private javax.swing.JCheckBox koltuk10;
    private javax.swing.JCheckBox koltuk11;
    private javax.swing.JCheckBox koltuk12;
    private javax.swing.JCheckBox koltuk13;
    private javax.swing.JCheckBox koltuk14;
    private javax.swing.JCheckBox koltuk15;
    private javax.swing.JCheckBox koltuk16;
    private javax.swing.JCheckBox koltuk17;
    private javax.swing.JCheckBox koltuk18;
    private javax.swing.JCheckBox koltuk19;
    private javax.swing.JCheckBox koltuk2;
    private javax.swing.JCheckBox koltuk20;
    private javax.swing.JCheckBox koltuk21;
    private javax.swing.JCheckBox koltuk22;
    private javax.swing.JCheckBox koltuk23;
    private javax.swing.JCheckBox koltuk24;
    private javax.swing.JCheckBox koltuk25;
    private javax.swing.JCheckBox koltuk26;
    private javax.swing.JCheckBox koltuk27;
    private javax.swing.JCheckBox koltuk28;
    private javax.swing.JCheckBox koltuk29;
    private javax.swing.JCheckBox koltuk3;
    private javax.swing.JCheckBox koltuk30;
    private javax.swing.JCheckBox koltuk4;
    private javax.swing.JCheckBox koltuk5;
    private javax.swing.JCheckBox koltuk6;
    private javax.swing.JCheckBox koltuk7;
    private javax.swing.JCheckBox koltuk8;
    private javax.swing.JCheckBox koltuk9;
    private javax.swing.JLabel secilen_koltuklar;
    private javax.swing.JLabel sofor_koltugu;
    // End of variables declaration//GEN-END:variables
}
