/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje2.deneme.pkg1;

/**
 *
 * @author reyha
 */
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
 
  
public class rezervasyon extends javax.swing.JFrame {
        
        private koltuk_sayisi30 koltuk_sayisi30;
        private koltuk_sayisi20 koltuk_sayisi20;
        private koltuk_sayisi15 koltuk_sayisi15;
        private koltuk_sayisi25 koltuk_sayisi25;
        private static final int FIRMA_TURU_INDEX = 3;
        private static final int ARAC_TURU_INDEX = 4;
        

    
    public rezervasyon() {
        

        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    class karaYolu_sefer
    {
        private String ulasim_Turu = "karayolu";
        private String firma_Turu ;
        private String arac_Turu ;
        private String sefer_Numarasi ;
        private String bilet_Fiyati ;
        
        public karaYolu_sefer(String[] firma_Turu ,String[] arac_Turu,String[] sefer_Numarasi,String[] bilet_Fiyati)
        {
            this.firma_Turu = firma_Turu[new Random().nextInt(firma_Turu.length)];
            this.arac_Turu = arac_Turu[new Random().nextInt(arac_Turu.length)];
            this.sefer_Numarasi = sefer_Numarasi[new Random().nextInt(sefer_Numarasi.length)];
            this.bilet_Fiyati = bilet_Fiyati[new Random().nextInt(bilet_Fiyati.length)];
            
        }
        
        public String getUlasim_Turu() 
        {
            return ulasim_Turu;
        }
        
        public String getFirma_Turu() 
        {
            return firma_Turu;
        }

        public String getArac_Turu() 
        {
            return arac_Turu;
        }

        public String getSefer_Numarasi() 
        {
            return sefer_Numarasi;
        }

        public String getBilet_Fiyati() 
        {
            return bilet_Fiyati;
        }
        
        
    }
    class demirYolu_sefer
    {
        private String ulasim_Turu ="demiryolu";
        private String firma_Turu ;
        private String arac_Turu;
        private String sefer_Numarasi;
        private String bilet_Fiyati;
        
        public demirYolu_sefer(String[] firma_Turu ,String[] arac_Turu,String[] sefer_Numarasi,String[] bilet_Fiyati)
        {
            this.firma_Turu = firma_Turu[new Random().nextInt(firma_Turu.length)];
            this.arac_Turu = arac_Turu[new Random().nextInt(arac_Turu.length)];
            this.sefer_Numarasi = sefer_Numarasi[new Random().nextInt(sefer_Numarasi.length)];
            this.bilet_Fiyati = bilet_Fiyati[new Random().nextInt(bilet_Fiyati.length)];
        }
        
        public String getUlasim_Turu() 
        {
            return ulasim_Turu;
        }
        
        public String getFirma_Turu() 
        {
            return firma_Turu;
        }

        public String getArac_Turu() 
        {
            return arac_Turu;
        }

        public String getSefer_Numarasi() 
        {
            return sefer_Numarasi;
        }

        public String getBilet_Fiyati() 
        {
            return bilet_Fiyati;
        }
        
    }
    class havaYolu_sefer
    {
        private String ulasim_Turu ="havayolu";
        private String firma_Turu ;
        private String arac_Turu;
        private String sefer_Numarasi;
        private String bilet_Fiyati;
        
        public havaYolu_sefer(String[] firma_Turu ,String[] arac_Turu,String[] sefer_Numarasi,String[] bilet_Fiyati)
        {
            this.firma_Turu = firma_Turu[new Random().nextInt(firma_Turu.length)];
            this.arac_Turu = arac_Turu[new Random().nextInt(arac_Turu.length)];
            this.sefer_Numarasi = sefer_Numarasi[new Random().nextInt(sefer_Numarasi.length)];
            this.bilet_Fiyati = bilet_Fiyati[new Random().nextInt(bilet_Fiyati.length)];
        }
        
        public String getUlasim_Turu() 
        {
            return ulasim_Turu;
        }
        
        public String getFirma_Turu() 
        {
            return firma_Turu;
        }

        public String getArac_Turu() 
        {
            return arac_Turu;
        }

        public String getSefer_Numarasi() 
        {
            return sefer_Numarasi;
        }

        public String getBilet_Fiyati() 
        {
            return bilet_Fiyati;
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menubuton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        variscbox = new javax.swing.JComboBox<>();
        kalkiscbox = new javax.swing.JComboBox<>();
        tarihcbox = new javax.swing.JComboBox<>();
        yolcusayisitext = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        sefertablosu = new javax.swing.JTable();
        seferbulbuton = new javax.swing.JButton();
        koltuk_sec = new javax.swing.JButton();
        mesaj_yazisi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        menubuton.setBackground(new java.awt.Color(102, 102, 102));
        menubuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menubuton.setForeground(new java.awt.Color(255, 255, 255));
        menubuton.setText("GERİ");
        menubuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubutonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Kalkış Noktası :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Varış Noktası :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Yolculuk Tarihi: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Seyahat Edecek Yolcu Sayısı: ");

        variscbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul", "Ankara", "Kocaeli", "Bilecik", "Eskisehir", "Konya" }));
        variscbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variscboxActionPerformed(evt);
            }
        });

        kalkiscbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul", "Ankara", "Kocaeli", "Bilecik", "Eskisehir", "Konya" }));
        kalkiscbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalkiscboxActionPerformed(evt);
            }
        });

        tarihcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 Aralik", "5 Aralik", "6 Aralik", "7 Aralik", "8 Aralik", "9 Aralik", "10 Aralik", " " }));
        tarihcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihcboxActionPerformed(evt);
            }
        });

        yolcusayisitext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yolcusayisitextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yolcusayisitext)
                    .addComponent(tarihcbox, 0, 140, Short.MAX_VALUE)
                    .addComponent(variscbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kalkiscbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kalkiscbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(variscbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarihcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yolcusayisitext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        sefertablosu.setBackground(new java.awt.Color(204, 204, 204));
        sefertablosu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        sefertablosu.setForeground(new java.awt.Color(102, 102, 102));
        sefertablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kalkış Noktası", "varıs noktası", "ulasım turu", "firma", "arac", "sefer no", "bilet fiyatı", "yolculuk tarihi", "bilet sayısı"
            }
        ));
        sefertablosu.setSelectionBackground(new java.awt.Color(153, 153, 153));
        sefertablosu.setSelectionForeground(new java.awt.Color(255, 102, 102));
        sefertablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sefertablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sefertablosu);

        seferbulbuton.setBackground(new java.awt.Color(51, 102, 255));
        seferbulbuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seferbulbuton.setForeground(new java.awt.Color(255, 255, 255));
        seferbulbuton.setText("Sefer Bul");
        seferbulbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seferbulbutonActionPerformed(evt);
            }
        });

        koltuk_sec.setBackground(new java.awt.Color(153, 153, 255));
        koltuk_sec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        koltuk_sec.setForeground(new java.awt.Color(255, 255, 255));
        koltuk_sec.setText("Koltuk Seç");
        koltuk_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koltuk_secActionPerformed(evt);
            }
        });

        mesaj_yazisi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mesaj_yazisi.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seferbulbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltuk_sec, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(menubuton))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(menubuton)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(seferbulbuton)
                        .addGap(20, 20, 20)
                        .addComponent(koltuk_sec)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void seferbul() {
    String selectedKalkis = (String) kalkiscbox.getSelectedItem();
    String selectedVaris = (String) variscbox.getSelectedItem();
    String selectedTarih = (String) tarihcbox.getSelectedItem();
    mesaj_yazisi.setText("");  
    DefaultTableModel tableModel = (DefaultTableModel) sefertablosu.getModel();
    tableModel.setRowCount(0);
     
    if((selectedKalkis.equals("Konya") && selectedVaris.equals("Ankara")) || ((selectedKalkis.equals("Ankara") && selectedVaris.equals("Konya"))))
     {
              mesaj_yazisi.setText("Böyle bir sefer bulunamamaktadir.");  
     }
    
    
    // Kalkış ve varış noktalarına göre sefer bilgilerini ekle
    // Burada örnek veriler kullanılmıştır, gerçek veri kaynağınıza uygun şekilde güncelleyebilirsiniz.
     if (selectedKalkis.equals("Istanbul") && selectedVaris.equals("Ankara"))
     {
                 int random_SeferSayisi = new Random().nextInt(4) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"A firmasi", "B firmasi"};
                 String[] arac_Turu = {"otobus 1", "otobus 2"};
                 String[] sefer_Numarasi = {"sefer 3 "};
                 String[] bilet_Fiyati = { "300TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1"};
                 String[] sefer_Numarasi2 = {"sefer 1 "};
                 String[] bilet_Fiyati2 = { "250TL"}; 
                 String[] firma_Turu3 = {"F firmasi"};
                 String[] arac_Turu3 = {"ucak 1","ucak 2"};
                 String[] sefer_Numarasi3 = {"sefer 6 "};
                 String[] bilet_Fiyati3 = { "1000TL"};

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                      //havayolu                      
                      havaYolu_sefer havaYolu_sefer = new havaYolu_sefer(firma_Turu3,arac_Turu3,sefer_Numarasi3,bilet_Fiyati3);

                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, havaYolu_sefer.getUlasim_Turu(),havaYolu_sefer.getFirma_Turu(),havaYolu_sefer.getArac_Turu(),havaYolu_sefer.getSefer_Numarasi(), havaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});                      
                 }                
     }
    
     
     if (selectedKalkis.equals("Istanbul") && selectedVaris.equals("Kocaeli"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"A firmasi", "B firmasi","C firmasi"};
                 String[] arac_Turu = {"otobus 1", "otobus 2"};
                 String[] sefer_Numarasi = {"sefer 3","4. sefer"};
                 String[] bilet_Fiyati = { "50TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1","tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 1 ","sefer 2 "};
                 String[] bilet_Fiyati2 = { "50TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Istanbul") && selectedVaris.equals("Eskisehir"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"B firmasi","C firmasi"};
                 String[] arac_Turu = {"otobus 1", "otobus 2"};
                 String[] sefer_Numarasi = {"4. sefer"};
                 String[] bilet_Fiyati = { "150TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1","tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 1 ","sefer 2"};
                 String[] bilet_Fiyati2 = { "200TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Istanbul") && selectedVaris.equals("Konya"))
     {
                 int random_SeferSayisi = new Random().nextInt(4) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"C firmasi", "B firmasi"};
                 String[] arac_Turu = {"otobus 1", "otobus 2"};
                 String[] sefer_Numarasi = {"sefer 4"};
                 String[] bilet_Fiyati = { "300TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 2 "};
                 String[] bilet_Fiyati2 = { "300TL"}; 
                 String[] firma_Turu3 = {"C firmasi"};
                 String[] arac_Turu3 = {"ucak 1","ucak 2"};
                 String[] sefer_Numarasi3 = {"sefer 5"};
                 String[] bilet_Fiyati3 = { "1200TL"};

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                      //havayolu                      
                      havaYolu_sefer havaYolu_sefer = new havaYolu_sefer(firma_Turu3,arac_Turu3,sefer_Numarasi3,bilet_Fiyati3);

                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, havaYolu_sefer.getUlasim_Turu(),havaYolu_sefer.getFirma_Turu(),havaYolu_sefer.getArac_Turu(),havaYolu_sefer.getSefer_Numarasi(), havaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});                      
                 }                
     }
     
     
     if (selectedKalkis.equals("Istanbul") && selectedVaris.equals("Bilecik"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();                
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1","tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 1 ","sefer 2 "};
                 String[] bilet_Fiyati2 = { "150TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {                                                          
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     
     if (selectedKalkis.equals("Kocaeli") && selectedVaris.equals("Istanbul"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"A firmasi","B firmasi","C firmasi"};
                 String[] arac_Turu = {"otobus 1", "otobus 2"};
                 String[] sefer_Numarasi = {"3. sefer","4. sefer"};
                 String[] bilet_Fiyati = { "50TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1","tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 1 ","sefer 2 "};
                 String[] bilet_Fiyati2 = { "50TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Kocaeli") && selectedVaris.equals("Ankara"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"B firmasi","A firmasi"};
                 String[] arac_Turu = {"otobus 1", "otobus 2"};
                 String[] sefer_Numarasi = {"4. sefer"};
                 String[] bilet_Fiyati = { "400TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1"};
                 String[] sefer_Numarasi2 = {"sefer 1 "};
                 String[] bilet_Fiyati2 = { "200TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     
     if (selectedKalkis.equals("Kocaeli") && selectedVaris.equals("Eskisehir"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"B firmasi","C firmasi"};
                 String[] arac_Turu = {"otobus 1", "otobus 2"};
                 String[] sefer_Numarasi = {"4. sefer"};
                 String[] bilet_Fiyati = { "100TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1","tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 1","sefer 2 "};
                 String[] bilet_Fiyati2 = { "100TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Kocaeli") && selectedVaris.equals("Konya"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"B firmasi","C firmasi"};
                 String[] arac_Turu = {"otobus 2", "otobus 1"};
                 String[] sefer_Numarasi = {"4. sefer"};
                 String[] bilet_Fiyati = { "250TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 2 "};
                 String[] bilet_Fiyati2 = { "250TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     
     if (selectedKalkis.equals("Kocaeli") && selectedVaris.equals("Bilecik"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();                
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1","tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 1 ","sefer 2 "};
                 String[] bilet_Fiyati2 = { "50TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {                                                          
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     
     if (selectedKalkis.equals("Ankara") && selectedVaris.equals("Istanbul"))
     {
                 int random_SeferSayisi = new Random().nextInt(4) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"A firmasi", "B firmasi"};
                 String[] arac_Turu = {"otobus 1", "otobus 2"};
                 String[] sefer_Numarasi = {"sefer 3 "};
                 String[] bilet_Fiyati = { "300TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1"};
                 String[] sefer_Numarasi2 = {"sefer 1 "};
                 String[] bilet_Fiyati2 = { "250TL"}; 
                 String[] firma_Turu3 = {"F firmasi"};
                 String[] arac_Turu3 = {"ucak 1","ucak 2"};
                 String[] sefer_Numarasi3 = {"sefer 6"};
                 String[] bilet_Fiyati3 = { "1000TL"};

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                      //havayolu                      
                      havaYolu_sefer havaYolu_sefer = new havaYolu_sefer(firma_Turu3,arac_Turu3,sefer_Numarasi3,bilet_Fiyati3);

                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, havaYolu_sefer.getUlasim_Turu(),havaYolu_sefer.getFirma_Turu(),havaYolu_sefer.getArac_Turu(),havaYolu_sefer.getSefer_Numarasi(), havaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});                      
                 }                
     }
     
     
     if (selectedKalkis.equals("Ankara") && selectedVaris.equals("Kocaeli"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"B firmasi","A firmasi"};
                 String[] arac_Turu = {"otobus 2", "otobus 1"};
                 String[] sefer_Numarasi = {"3. sefer"};
                 String[] bilet_Fiyati = { "400TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1"};
                 String[] sefer_Numarasi2 = {"sefer 1"};
                 String[] bilet_Fiyati2 = { "200TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     
     if (selectedKalkis.equals("Ankara") && selectedVaris.equals("Eskisehir"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();                
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1"};
                 String[] sefer_Numarasi2 = {"sefer 1 "};
                 String[] bilet_Fiyati2 = { "100TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {                                                          
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     
     if (selectedKalkis.equals("Ankara") && selectedVaris.equals("Bilecik"))
     {
                 int random_SeferSayisi = new Random().nextInt(4) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();                
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1"};
                 String[] sefer_Numarasi2 = {"sefer 1 "};
                 String[] bilet_Fiyati2 = { "150TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {                                                          
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Eskisehir") && selectedVaris.equals("Istanbul"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"B firmasi","C firmasi"};
                 String[] arac_Turu = {"otobus 2", "otobus 1"};
                 String[] sefer_Numarasi = {"4. sefer"};
                 String[] bilet_Fiyati = { "150TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1","tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 1 ","sefer 2"};
                 String[] bilet_Fiyati2 = { "200TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Eskisehir") && selectedVaris.equals("Kocaeli"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"B firmasi","C firmasi"};
                 String[] arac_Turu = {"otobus 2", "otobus 1"};
                 String[] sefer_Numarasi = {"4. sefer"};
                 String[] bilet_Fiyati = { "100TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1","tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 1 ","sefer 2"};
                 String[] bilet_Fiyati2 = { "100TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Eskisehir") && selectedVaris.equals("Konya"))
     {
                 int random_SeferSayisi = new Random().nextInt(4) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"B firmasi","C firmasi"};
                 String[] arac_Turu = {"otobus 2", "otobus 1"};
                 String[] sefer_Numarasi = {"4. sefer"};
                 String[] bilet_Fiyati = { "150TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 2"};
                 String[] bilet_Fiyati2 = { "150TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Eskisehir") && selectedVaris.equals("Bilecik"))
     {
                 int random_SeferSayisi = new Random().nextInt(4) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();                
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1","tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 1 ","sefer 2"};
                 String[] bilet_Fiyati2 = { "50TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {                                                          
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Eskisehir") && selectedVaris.equals("Ankara"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();                
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1"};
                 String[] sefer_Numarasi2 = {"sefer 1 "};
                 String[] bilet_Fiyati2 = { "100TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {                                                          
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     
     if (selectedKalkis.equals("Konya") && selectedVaris.equals("Istanbul"))
     {
                 int random_SeferSayisi = new Random().nextInt(5) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"C firmasi", "B firmasi"};
                 String[] arac_Turu = {"otobus 1", "otobus 2"};
                 String[] sefer_Numarasi = {"sefer 4 "};
                 String[] bilet_Fiyati = { "300TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 2 "};
                 String[] bilet_Fiyati2 = { "300TL"}; 
                 String[] firma_Turu3 = {"C firmasi"};
                 String[] arac_Turu3 = {"ucak 1","ucak 2"};
                 String[] sefer_Numarasi3 = {"sefer 5"};
                 String[] bilet_Fiyati3 = { "1200TL"};

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                      //havayolu                      
                      havaYolu_sefer havaYolu_sefer = new havaYolu_sefer(firma_Turu3,arac_Turu3,sefer_Numarasi3,bilet_Fiyati3);

                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, havaYolu_sefer.getUlasim_Turu(),havaYolu_sefer.getFirma_Turu(),havaYolu_sefer.getArac_Turu(),havaYolu_sefer.getSefer_Numarasi(), havaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});                      
                 }                
     }
     
     if (selectedKalkis.equals("Konya") && selectedVaris.equals("Kocaeli"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"B firmasi","C firmasi"};
                 String[] arac_Turu = {"otobus 2", "otobus 1"};
                 String[] sefer_Numarasi = {"4. sefer"};
                 String[] bilet_Fiyati = { "250TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 2"};
                 String[] bilet_Fiyati2 = { "250TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Konya") && selectedVaris.equals("Eskisehir"))
     {
                 int random_SeferSayisi = new Random().nextInt(3) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();
                 String[] firma_Turu = {"B firmasi","C firmasi"};
                 String[] arac_Turu = {"otobus 2", "otobus 1"};
                 String[] sefer_Numarasi = {"4. sefer"};
                 String[] bilet_Fiyati = { "150TL"};
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 2"};
                 String[] bilet_Fiyati2 = { "150TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {
                     //karayolu                                            
                      karaYolu_sefer karaYolu_sefer = new karaYolu_sefer(firma_Turu,arac_Turu,sefer_Numarasi,bilet_Fiyati);                                            
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, karaYolu_sefer.getUlasim_Turu(),karaYolu_sefer.getFirma_Turu(),karaYolu_sefer.getArac_Turu(),karaYolu_sefer.getSefer_Numarasi(), karaYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Konya") && selectedVaris.equals("Bilecik"))
     {
                 int random_SeferSayisi = new Random().nextInt(4) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();                
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 2 "};
                 String[] bilet_Fiyati2 = { "200TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {                                                          
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Bilecik") && selectedVaris.equals("Istanbul"))
     {
                 int random_SeferSayisi = new Random().nextInt(4) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();                
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1","tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 1 ","sefer 2"};
                 String[] bilet_Fiyati2 = { "150TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {                                                          
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Bilecik") && selectedVaris.equals("Kocaeli"))
     {
                 int random_SeferSayisi = new Random().nextInt(4) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();                
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1","tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 1 ","sefer 2"};
                 String[] bilet_Fiyati2 = { "50TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {                                                          
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Bilecik") && selectedVaris.equals("Ankara"))
     {
                 int random_SeferSayisi = new Random().nextInt(4) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();                
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1"};
                 String[] sefer_Numarasi2 = {"sefer 1 "};
                 String[] bilet_Fiyati2 = { "150TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {                                                          
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     if (selectedKalkis.equals("Bilecik") && selectedVaris.equals("Eskisehir"))
     {
                 int random_SeferSayisi = new Random().nextInt(4) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();                
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 1","tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 1 ","sefer 2"};
                 String[] bilet_Fiyati2 = { "50TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {                                                          
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     
     if (selectedKalkis.equals("Bilecik") && selectedVaris.equals("Konya"))
     {
                 int random_SeferSayisi = new Random().nextInt(4) + 1;
                 String yolcuSayisi = yolcusayisitext.getText();                
                 String[] firma_Turu2 = {"D firmasi"};
                 String[] arac_Turu2 = {"tren 2","tren 3"};
                 String[] sefer_Numarasi2 = {"sefer 2"};
                 String[] bilet_Fiyati2 = { "200TL"}; 
                 

                 for(int i=0 ; i< random_SeferSayisi ; i++)
                 {                                                          
                      //demiryolu                      
                      demirYolu_sefer demirYolu_sefer = new demirYolu_sefer(firma_Turu2,arac_Turu2,sefer_Numarasi2,bilet_Fiyati2);                                            
                                 
                      tableModel.addRow(new Object[]{selectedKalkis, selectedVaris, demirYolu_sefer.getUlasim_Turu(),demirYolu_sefer.getFirma_Turu(),demirYolu_sefer.getArac_Turu(),demirYolu_sefer.getSefer_Numarasi(), demirYolu_sefer.getBilet_Fiyati() , selectedTarih, yolcuSayisi});
                 }                
     }
     
     
    // Diğer kalkış-varış noktaları için benzer şekilde ekleyebilirsiniz.
    tableModel.fireTableDataChanged(); // Tabloyu güncelle
}

    
    
    private void sefertablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sefertablosuMouseClicked
       int secilirow=sefertablosu.getSelectedRow();
       DefaultTableModel model=(DefaultTableModel) sefertablosu.getModel();
       kalkiscbox.setSelectedItem(model.getValueAt(secilirow,0).toString());
       variscbox.setSelectedItem(model.getValueAt(secilirow,1).toString());
       tarihcbox.setSelectedItem(model.getValueAt(secilirow,7).toString());
       yolcusayisitext.setText(model.getValueAt(secilirow,8).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_sefertablosuMouseClicked

    private void kalkiscboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalkiscboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kalkiscboxActionPerformed

    private void variscboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variscboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_variscboxActionPerformed

    private void tarihcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihcboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarihcboxActionPerformed

    private void yolcusayisitextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yolcusayisitextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yolcusayisitextActionPerformed

    private void seferbulbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seferbulbutonActionPerformed
       
        seferbul();
// TODO add your handling code here:
    }//GEN-LAST:event_seferbulbutonActionPerformed

    private void menubutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubutonActionPerformed
    
     bilet_al menuyedon = new bilet_al();
     menuyedon.setVisible(true);
     
     this.setVisible(false);        

// TODO add your handling code here:
    }//GEN-LAST:event_menubutonActionPerformed

    private void koltuk_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koltuk_secActionPerformed
        
        DefaultTableModel model=(DefaultTableModel) sefertablosu.getModel();
        
        int secilirow=sefertablosu.getSelectedRow();
        
        if(secilirow == -1)
        {
            if(sefertablosu.getRowCount()==0)
            { 
                mesaj_yazisi.setText("Tablo şu anda boş");
            }
            else
            {
                 mesaj_yazisi.setText("bir sefer seçin");
            }
            
        }
        else
        {
                              
                              String firmaTuru = (String) model.getValueAt(secilirow, FIRMA_TURU_INDEX); // FIRMA_TURU_INDEX uygun indeksi girin
                              String aracTuru = (String) model.getValueAt(secilirow, ARAC_TURU_INDEX);   // ARAC_TURU_INDEX uygun indeksi girin
                            if( firmaTuru.equals("A firmasi")&& aracTuru.equals("otobus 1"))
                            {

                               koltuk_sayisi20 koltuk =new koltuk_sayisi20();
                               koltuk.setVisible(true);
                               
                               this.setVisible(false);
                            }
                            if( firmaTuru.equals("A firmasi")&& aracTuru.equals("otobus 2"))
                            {

                               koltuk_sayisi15 koltuk =new koltuk_sayisi15();
                               koltuk.setVisible(true);
                               
                               this.setVisible(false);
                            }
                            if( firmaTuru.equals("B firmasi")&& aracTuru.equals("otobus 1"))
                            {

                               koltuk_sayisi15 koltuk =new koltuk_sayisi15();
                               koltuk.setVisible(true);
                               
                               this.setVisible(false);
                            }
                            if( firmaTuru.equals("B firmasi")&& aracTuru.equals("otobus 2"))
                            {

                               koltuk_sayisi20 koltuk =new koltuk_sayisi20();
                               koltuk.setVisible(true);
                               
                               this.setVisible(false);
                            }
                            if( firmaTuru.equals("C firmasi")&& aracTuru.equals("otobus 1"))
                            {

                               koltuk_sayisi20 koltuk =new koltuk_sayisi20();
                               koltuk.setVisible(true);
                               
                               this.setVisible(false);
                            }
                            if( firmaTuru.equals("C firmasi")&& aracTuru.equals("ucak 1"))
                            {

                               koltuk_sayisi30 koltuk =new koltuk_sayisi30();
                               koltuk.setVisible(true);
                               
                               this.setVisible(false);
                            }
                            if( firmaTuru.equals("C firmasi")&& aracTuru.equals("ucak 2"))
                            {

                               koltuk_sayisi30 koltuk =new koltuk_sayisi30();
                               koltuk.setVisible(true);
                               
                               this.setVisible(false);
                            }
                            if( firmaTuru.equals("D firmasi")&& aracTuru.equals("tren 1"))
                            {

                               koltuk_sayisi25 koltuk =new koltuk_sayisi25();
                               koltuk.setVisible(true);
                               
                               this.setVisible(false);
                            }
                            if( firmaTuru.equals("D firmasi")&& aracTuru.equals("tren 2"))
                            {

                               koltuk_sayisi25 koltuk =new koltuk_sayisi25();
                               koltuk.setVisible(true);
                               
                               this.setVisible(false);
                            }
                            if( firmaTuru.equals("D firmasi")&& aracTuru.equals("tren 3"))
                            {

                               koltuk_sayisi25 koltuk =new koltuk_sayisi25();
                               koltuk.setVisible(true);
                               
                               this.setVisible(false);
                            }
                            if( firmaTuru.equals("F firmasi")&& aracTuru.equals("ucak 1"))
                            {

                               koltuk_sayisi30 koltuk =new koltuk_sayisi30();
                               koltuk.setVisible(true);
                               
                               this.setVisible(false);
                            }
                            if( firmaTuru.equals("F firmasi")&& aracTuru.equals("ucak 2"))
                            {

                               koltuk_sayisi30 koltuk =new koltuk_sayisi30();
                               koltuk.setVisible(true);
                               
                               this.setVisible(false);
                            }
            
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_koltuk_secActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rezervasyon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rezervasyon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rezervasyon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rezervasyon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rezervasyon().setVisible(true);
            }
        });
         java.awt.EventQueue.invokeLater(() -> {
            rezervasyon rez = new rezervasyon();
            rez.setVisible(true);

            // Başlangıçta araçları listele
            rez.seferbul();
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kalkiscbox;
    private javax.swing.JButton koltuk_sec;
    private javax.swing.JButton menubuton;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JButton seferbulbuton;
    private javax.swing.JTable sefertablosu;
    private javax.swing.JComboBox<String> tarihcbox;
    private javax.swing.JComboBox<String> variscbox;
    private javax.swing.JTextField yolcusayisitext;
    // End of variables declaration//GEN-END:variables
}
