/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje2.deneme.pkg1;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author reyha
 */
/*
class secili_koltuklar
{
    private String seciliKoltuklar;

    public secili_koltuklar(String seciliKoltuklar) {
        this.seciliKoltuklar = seciliKoltuklar;
    }
    
    public void setSeciliKoltuklar(String seciliKoltuklar) {
        this.seciliKoltuklar = seciliKoltuklar;
    }
    
    public String getSeciliKoltuklar() {
        return seciliKoltuklar;
    }
       
}
*/
public class yolcubilgileri extends javax.swing.JFrame {
    
    /**
     *
     * @param selectedKoltuklar
     */
    /*    
    static void setSelectedKoltuklar(Set<String> selectedKoltuklar) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    */
    
  
    
    public yolcubilgileri() {
        initComponents();
        
    }
    
    
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menubuton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adsoyadgir = new javax.swing.JTextField();
        mailgir = new javax.swing.JTextField();
        dogumgir = new javax.swing.JTextField();
        tcgir = new javax.swing.JTextField();
        telgir = new javax.swing.JTextField();
        yolcucikarbuton = new javax.swing.JButton();
        yolcueklebuton = new javax.swing.JButton();
        mesajyazisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        biletbilgileritablosu = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        odebuton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        menubuton.setBackground(new java.awt.Color(102, 102, 102));
        menubuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menubuton.setForeground(new java.awt.Color(255, 255, 255));
        menubuton.setText("GERİ");
        menubuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubutonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Seçtiğiniz Yolcuların Bilgilerini Giriniz!!!");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setText("Yolcu Ad-Soyad:");

        jLabel3.setText("E-mail:");

        jLabel4.setText("Yolcu TC:");

        jLabel5.setText("Yolcu Doğum Tarihi:");

        jLabel6.setText("Telefon No:");

        adsoyadgir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adsoyadgirActionPerformed(evt);
            }
        });

        mailgir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailgirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tcgir)
                    .addComponent(mailgir)
                    .addComponent(adsoyadgir)
                    .addComponent(dogumgir)
                    .addComponent(telgir, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(adsoyadgir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mailgir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tcgir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dogumgir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(telgir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        yolcucikarbuton.setBackground(new java.awt.Color(255, 0, 0));
        yolcucikarbuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yolcucikarbuton.setForeground(new java.awt.Color(255, 255, 255));
        yolcucikarbuton.setText("Yolcu Çıkar ");
        yolcucikarbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yolcucikarbutonActionPerformed(evt);
            }
        });

        yolcueklebuton.setBackground(new java.awt.Color(51, 204, 0));
        yolcueklebuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yolcueklebuton.setForeground(new java.awt.Color(255, 255, 255));
        yolcueklebuton.setText("Yolcu Ekle ");
        yolcueklebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yolcueklebutonActionPerformed(evt);
            }
        });

        biletbilgileritablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ad Soyad", "E-mail", "TC", "Doğum Tarihi", "Telefon No"
            }
        ));
        biletbilgileritablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biletbilgileritablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(biletbilgileritablosu);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BİLET BİLGİLERİ");

        odebuton.setBackground(new java.awt.Color(255, 153, 255));
        odebuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        odebuton.setForeground(new java.awt.Color(255, 255, 255));
        odebuton.setText("Ödeme Yap");
        odebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odebutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(menubuton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(odebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yolcueklebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yolcucikarbuton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesajyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 65, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(menubuton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(yolcueklebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yolcucikarbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(mesajyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(odebuton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adsoyadgirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adsoyadgirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adsoyadgirActionPerformed

    private void mailgirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailgirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailgirActionPerformed

    private void odebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odebutonActionPerformed
    
       List<String> seciliKoltuklar = KoltukBilgileri.getSeciliKoltuklar();
          
       if (biletbilgileritablosu.getRowCount() == 0) 
      {
        String message = "YOLCU EKLENMEDİ. LÜTFEN YOLCU BİLGİLERİNİ GİRİNİZ.";
        JOptionPane.showMessageDialog(this, message);
      } 
      else 
      {
        // Yolcu bilgilerini içeren bir ileti oluştur
        StringBuilder messageBuilder = new StringBuilder("BİLETLERİNİZ BAŞARIYLA OLUŞTURULDU.\n\n\n");
        messageBuilder.append("YOLCU BİLGİLERİ :\n");
        

        for (int i = 0; i < biletbilgileritablosu.getRowCount(); i++) 
        {
            messageBuilder.append("Ad Soyad : ").append(biletbilgileritablosu.getValueAt(i, 0)).append("\n");
            messageBuilder.append("E-mail : ").append(biletbilgileritablosu.getValueAt(i, 1)).append("\n");
            messageBuilder.append("TC : ").append(biletbilgileritablosu.getValueAt(i, 2)).append("\n");
            messageBuilder.append("Doğum Tarihi : ").append(biletbilgileritablosu.getValueAt(i, 3)).append("\n");
            messageBuilder.append("Telefon : ").append(biletbilgileritablosu.getValueAt(i, 4)).append("\n\n");
            
        }
        messageBuilder.append("Koltuk numaralari: ").append(seciliKoltuklar.toString());
        JOptionPane.showMessageDialog(this, messageBuilder.toString());       
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_odebutonActionPerformed
     
    private void yolcueklebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yolcueklebutonActionPerformed

        mesajyazisi.setText("");
     javax.swing.table.DefaultTableModel model=(javax.swing.table.DefaultTableModel) biletbilgileritablosu.getModel();
      mesajyazisi.setText("");

      if(adsoyadgir.getText().trim().equals("") ||mailgir.getText().trim().equals("")|| tcgir.getText().trim().equals("") ||dogumgir.getText().trim().equals("") ||telgir.getText().trim().equals(""))
      {
          mesajyazisi.setText("Lutfen bilgileri giriniz!(Tüm alanlarin girilmesi zorunludur)");
      }
      else
      {
          Object[] eklenecek = {adsoyadgir.getText(),mailgir.getText(),tcgir.getText(),dogumgir.getText(),telgir.getText()};
          model.addRow(eklenecek);    
           mesajyazisi.setText("Yolcu eklendi");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_yolcueklebutonActionPerformed

    private void biletbilgileritablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biletbilgileritablosuMouseClicked
     javax.swing.table.DefaultTableModel model =(javax.swing.table.DefaultTableModel)biletbilgileritablosu.getModel();
     int secilirow=biletbilgileritablosu.getSelectedRow();
     adsoyadgir.setText(model.getValueAt(secilirow,0).toString());
     mailgir.setText(model.getValueAt(secilirow, 1).toString());
     tcgir.setText(model.getValueAt(secilirow, 2).toString());
     dogumgir.setText(model.getValueAt(secilirow, 3).toString());
     telgir.setText(model.getValueAt(secilirow,4).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_biletbilgileritablosuMouseClicked

    private void yolcucikarbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yolcucikarbutonActionPerformed
mesajyazisi.setText("");
        javax.swing.table.DefaultTableModel model =(javax.swing.table.DefaultTableModel)biletbilgileritablosu.getModel();
     int secilirow=biletbilgileritablosu.getSelectedRow();
     if(secilirow == -1)
     {  
         if(biletbilgileritablosu.getRowCount() == 0)
         { 
             mesajyazisi.setText("Tablo su anda bos");
         }
         else
         {
           mesajyazisi.setText("silinecek satir secin");   
         }
         
     }
         
     else
     {
         model.removeRow(secilirow);
         mesajyazisi.setText("urun basariyla silindi");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_yolcucikarbutonActionPerformed

    private void menubutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubutonActionPerformed
     rezervasyon geri= new rezervasyon();
     geri.setVisible(true);
     
     this.setVisible(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_menubutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yolcubilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yolcubilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yolcubilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yolcubilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new yolcubilgileri().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adsoyadgir;
    private javax.swing.JTable biletbilgileritablosu;
    private javax.swing.JTextField dogumgir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mailgir;
    private javax.swing.JButton menubuton;
    private javax.swing.JLabel mesajyazisi;
    private javax.swing.JButton odebuton;
    private javax.swing.JTextField tcgir;
    private javax.swing.JTextField telgir;
    private javax.swing.JButton yolcucikarbuton;
    private javax.swing.JButton yolcueklebuton;
    // End of variables declaration//GEN-END:variables
}
